### ISSUE TITLE
2016.2.x - tunneldiger watchdog restarts while connection active. 

### ISSUE THREAD

**Issue by Adorfer** [ffrl/ffrl-packages#10]
see https://forum.freifunk.net/t/l2tp-tunneldigger-thread/8726/84

FW: Gluon 2016.2.5, tunndeldigger 

PACKAGES_FFRL_PACKAGES_REPO=https://github.com/ffrl/ffrl-packages.git
PACKAGES_FFRL_PACKAGES_COMMIT=9ef54396cf79031b1b7e35af038b8a0f2ec1bd90
PACKAGES_FFRL_PACKAGES_BRANCH=Branch_v2016.2.x

![grafik](https://cloud.githubusercontent.com/assets/10302493/25066454/0ecb5bee-2226-11e7-91bd-08f347f4d2bc.png)

root@Friedrich-Kueppersbusch:~# ps |grep tunneldigger|wc -l
461

detailed list of running tunneldigger related tasks: 

    root@Friedrich-Kueppersbusch:~# ps |grep tunneldigger
     1070 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     1079 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     1244 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     1257 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     1289 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
     1367 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
     1475 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     1483 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     1533 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
     1644 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     1648 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     1740 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     1748 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     1756 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
     1955 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     1968 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     1976 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     1984 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     2078 root      1388 S    /bin/sh -c /usr/bin/tunneldigger-watchdog
     2083 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
     2101 root      1388 S    {tunneldigger-wa} /bin/sh /usr/bin/tunneldigger-watchdog
     2163 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
     2216 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
     2236 root      1452 S    {tunneldigger} /bin/sh /etc/rc.common /etc/init.d/tunneldigger restart
[cut]

complete list to be retrievable from:
https://paste.debian.net/927804/3

Any hints?

**Comment by CyrusOtter** [comment]
Does this issue occur on other nodes as well? 
It just a cronjob, so if it hangs its probably related to some issue with tunneldigger.
I suspect that the init script is hanging.

**Comment by Adorfer** [comment]
at the moment i am killing it via https://github.com/eulenfunk/packages/blob/v2016.2.x/gluon-quickfix/files/lib/gluon/quickfix/quickfix.sh

`[ "$(ps |grep -e tunneldigger\ restart -e tunneldigger-watchdog|wc -l)" -ge "6" ] && now_reboot "zu viele Tunneldigger-Restarts"`

**Comment by Adorfer** [comment]
obviously the /etc/init.d/tunneldigger "stop" does not complete

```
                start-stop-daemon -K -q -p $PIDFILE
                while test -d "/proc/${PID}"; do
                        echo "  waiting for tunneldigger to stop"
                        sleep 1
                done
                echo "  tunneldigger stopped"

```

Any hint what to do if the start-stop-demon fails and this loop is hanging?

**Comment by CyrusOtter** [comment]
Issue solved, we now run "killall -KILL tunneldigger" after stopping it to be on the safe side.

2017.X:
https://github.com/ffrl/ffrl-packages/tree/Branch_v2017.x

2016.2.X:
https://github.com/ffrl/ffrl-packages/tree/Branch_v2016.2.x
