### ISSUE TITLE
Tunneldigger enable=true / enable=1 in site.conf didnt work

### ISSUE THREAD

**Issue by Delta1977** [ffrl/ffrl-packages#5]
The Parameter   enable = true or enable = 1 have no funktion in site.conf.
  tunneldigger_mesh_vpn = {
        mtu = 1312,
        enabled = true,
        brokers = {

Whats the right option to enable Tunneldigger on default?

**Comment by paulinsche** [comment]
Look at https://github.com/ffrl/ffrl-packages/blob/master/gluon-config-mode-tunneldigger/files/lib/gluon/config-mode/wizard/0300-mesh-vpn.lua ... It looks like enabled = true should work. _enabled_, not _enable_.

**Comment by paulinsche** [comment]
In https://github.com/ffrl/ffrl-packages/blob/master/gluon-mesh-vpn-tunneldigger/files/lib/gluon/upgrade/400-mesh-vpn-tunneldigger :

tunneldigger_mesh_vpn = {
  broker = { 
    enabled = true,
 },
}

or 

tunneldigger_mesh_vpn = {
  enabled = true,
}

but I'm not sure.

**Comment by Delta1977** [comment]
Sorry, mistake (typing error) from me. Enabled = true did not work in the Broker section.

**Comment by paulinsche** [comment]
I tested it, and version 2 from above did not work. Have to investigate further.

**Comment by CyrusOtter** [comment]
Issue solved

**Comment by MPW1412** [comment]
What was the solution for this? enabled = true still doesn't work here in combination with skipping the configuration mode.

I don't see a commit to master relating this. Tested with v2016.1.5. What do I need to do to get a preconfigured L2TP image?
