### ISSUE TITLE
Tunneldigger-Pakete Upstream bringen

### ISSUE THREAD

**Issue by mweinelt** [ffrl/ffrl-packages#8]
Hallo @lcb01a,

nach einer nervenaufreibenden Diskussion mit L2TP/Tunneldigger-Befürwortern in #gluon stelle ich nun die folgenden Fragen:

- Gibt es einen Plan die für Gluon relevanten Pakete (`gluon-config-mode-tunneldigger`, `gluon-migrate-vpn`, `gluon-mesh-vpn-tunneldigger`, `gluon-tunneldigger-watchdog`) dorthin zu submitten?
- Gibt es einen Plan Tunneldigger nach `openwrt/packages` zu submitten?

Beste Grüße, hexa-

**Comment by CyrusOtter** [comment]
Resolved upstream, feature will be in gluon based on LEDE
